# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 6
    end
    config.vm.define "repo" do |repo|
        repo.vm.hostname = "repo"
        repo.vm.provision "shell", inline: <<-SHELL
        yum update
        yum install -y redhat-lsb-core wget nano rpmdevtools rpm-build createrepo yum-utils net-tools gcc nginx
        SHELL
    repo.vm.provision "shell",path: "start.sh"
    end
end