# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "debian/bookworm64",
	:disks => {
		:scsi10 => {
			:dfile => './scsi10.vdi',
			:size => "250",
			:port => 2
		},
		:scsi11 => {
                        :dfile => './scsi11.vdi',
                        :size => "250",
			:port => 3
		},
		:scsi12 => {
                        :dfile => './scsi12.vdi',
                        :size => "250",
			:port => 4
		},
		:scsi13 => {
                        :dfile => './scsi13.vdi',
                        :size => "250",
			:port => 5
		},
		:scsi14 => {
                        :dfile => './scsi14.vdi',
                        :size => "250",
			:port => 6
		}

	}	
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                  end

          end
                  if needsController = true
                     vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              apt-get update
	      apt-get install -y mdadm smartmontools hdparm gdisk parted
              mdadm --zero-superblock --force /dev/sd{b,c,d,e,f}
              mdadm --create /dev/md0 -l 0 -n 5 /dev/sd{b,c,d,e,f}
              echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
              mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
              parted -s /dev/md0 mklabel gpt
              parted /dev/md0 mkpart primary ext4 0% 20%
              parted /dev/md0 mkpart primary ext4 20% 40%
              parted /dev/md0 mkpart primary ext4 40% 60%
              parted /dev/md0 mkpart primary ext4 60% 80%
              parted /dev/md0 mkpart primary ext4 80% 100%
              for i in $(seq 1 5); do sudo mkfs.ext4 /dev/md0p$i; done
              mkdir -p /raid/part{1,2,3,4,5}
              for i in $(seq 1 5); do mount /dev/md0p$i /raid/part$i; done
  	  SHELL

      end
   end
end

