# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
    config.vm.define "systemd" do |systemd|
        systemd.vm.hostname = "systemd"
        systemd.vm.provision "shell", inline: <<-SHELL
        yum update
        SHELL
    end
end