# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :monitor => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :vm_name => 'monitor',
        :public => {
            bridge: 'wlo1',
            ip: '192.168.1.50',
            netmask: '255.255.255.0',
            gateway: '192.168.1.1'
        }
    },
    :client1 => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :vm_name => 'client1',
        :public => {
            bridge: 'wlo1',
            ip: '192.168.1.51',
            netmask: '255.255.255.0',
            gateway: '192.168.1.1'
        }
    },
    :client2 => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :vm_name => 'client2',
        :public => {
            bridge: 'wlo1',
            ip: '192.168.1.52',
            netmask: '255.255.255.0',
            gateway: '192.168.1.1'
        }
    },
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxconfig[:vm_name]
            box.vm.box_version = boxconfig[:box_version]
            box.vm.provider "virtualbox" do |v|
                v.memory = 1024
                v.cpus = 1
            end
            public_config = boxconfig[:public]
            box.vm.network "public_network", bridge: public_config[:bridge], ip: public_config[:ip], netmask: public_config[:netmask], gateway: public_config[:gateway]
            box.vm.provision "shell", inline: <<-SHELL
            yum update -y
            yum install vim wget net-tools -y
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
        end
    end
end