# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
  
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.become = "true"
    end
  
    config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 1024
    end
  
    config.vm.define "pam" do |pam|
      pam.vm.synced_folder ".","/vagrant", disabled: true
      pam.vm.network "private_network", ip: "192.168.56.10"
      pam.vm.hostname = "pam"
      pam.vm.provision "shell", inline: <<-SHELL
      sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl restart sshd.service
    SHELL
    end
  end